/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;
import todoApp.util.ConnectionFactory;
import java.sql.Connection;

public class App {
    public static void main(String[] args) {
        
        ConnectionFactory teste = new ConnectionFactory();
        
        Connection c = ; //Problema ao chamar método
        ConnectionFactory. //fechar conexão
    }
}
