/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;
import todoApp.util.ConnectionFactory;
import java.sql.Connection;
import java.sql.DriverManager;
import todoApp.model.project;

public class App {
    public static void main(String[] args) {
        
        ConnectionFactory teste = new ConnectionFactory();
        project.
        ConnectionFactory.//fechar conexão
                // Problema ao importar pacote.
    }
}
